# Generated by Django 4.1.4 on 2022-12-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_preorder_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorder',
            old_name='order_id',
            new_name='unique_id',
        ),
    ]
