# Generated by Django 4.1.4 on 2022-12-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_order_id_preorder_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('text_length', models.TextField(null=True)),
                ('unique_term', models.TextField(null=True)),
                ('unique_id', models.TextField(null=True)),
            ],
        ),
    ]
