# Generated by Django 4.1.4 on 2022-12-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='already_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
